#!/bin/sh
set -u
set -e

# Directory containing eclipse binary
eclipse=/opt/eclipse

$eclipse/eclipse \
  -nosplash -consoleLog \
  -application org.eclipse.ant.core.antRunner \
  -data /tmp/ws \
  -buildfile mirror.xml 2>&1 | tee mirror.log

